### ISSUE TITLE
SLots

### ISSUE THREAD

**Issue by Epik123** [Pullolo/MagicAbilities#1]
how do you change what slot your using for ur ability

**Comment by Pullolo** [comment]
Hi, You can change what ability is on which slot by using the /binds command.
Here is how the command works:
```/binds``` - displays your current binds
```/binds reset``` - resets binds to default ones
```/binds change <slot> <ability>``` - is used to change them

The ```<slot>``` is your hotbar slot 1st one is **0** last one is **8**
The ```<ability>``` is an ability id, to check what ability has which id, run the ```/binds``` command without previously modifying them and then the corresponding slot is an ability id (1st one is **0** last one is **8**)

For eg. here ability **Ice Bolt** has an id of **0**
![image](https://github.com/Pullolo/MagicAbilities/assets/99879934/e984c15a-dc5b-4265-95d6-e691c14c2084)

Let's say I want to have the **Ice Bolt** on slot **7**, to do that run ```/binds change 7 0```

**Comment by K1NGSL3YSUP3R6** [comment]
This actually helped alot thanks
