### ISSUE TITLE
?

### ISSUE THREAD

**Issue by hitpoop** [Pullolo/MagicAbilities#3]
How do you get powers in survival

**Comment by hitpoop** [comment]
pls answer soon

**Comment by Pullolo** [comment]
To get powers in general you need to be a server operator to have access to ```/setpower```, if you are just type ```/setpower <name> <power>```. That's all

**Comment by hitpoop** [comment]
> To get powers in general you need to be a server operator to have access to `/setpower`, if you are just type `/setpower <name> <power>`. That's all

DANG IT i wanted to use this for a smp

**Comment by Pullolo** [comment]
I mean you can, but you would have to set everyones power.
