### ISSUE TITLE
Well i dont have an issue

### ISSUE THREAD

**Issue by StyxWasTakenYT** [Pullolo/MagicAbilities#4]
Hi id like to contact you on Discord or something because i have some suggestions!

**Comment by StyxWasTakenYT** [comment]
btw my user on discord is styxwastaken

**Comment by StyxWasTakenYT** [comment]
and btw i did send you one!

**Comment by StyxWasTakenYT** [comment]
Just waiting!

**Comment by Pullolo** [comment]
I accepted the friend request.

**Comment by K1NGSL3YSUP3R6** [comment]
Do u have a discord server

**Comment by K1NGSL3YSUP3R6** [comment]
Bc I would like to ask u smt
